services:
  # Cấu hình cho Cơ sở dữ liệu PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: ticketing-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: ticketing_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Cấu hình cho Redis Cache & Hàng đợi khóa vé
  redis:
    image: redis:7-alpine
    container_name: ticketing-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
    external: true
    name: event-ticketing-hub_postgres_data