services:
  - type: web
    name: ticketing-api
    env: node
    plan: free
    buildCommand: npm_config_prefix=/opt/render/.npm-global npm install -g pnpm && pnpm install --frozen-lockfile && pnpm --filter api build && pnpm --filter api exec prisma generate
    startCommand: node apps/api/dist/main
    healthCheckPath: /auth/login
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        value: "6379"
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: "1025"
      - key: SMTP_FROM
        sync: false
      - key: VNPAY_TMN_CODE
        sync: false
      - key: VNPAY_HASH_SECRET
        sync: false
      - key: VNPAY_URL
        sync: false
      - key: VNPAY_RETURN_URL
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: BACKEND_URL
        sync: false
      - key: PORT
        value: "3000"
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_ANDROID_CLIENT_ID
        sync: false
