services:
  - type: web
    name: ticketing-api
    env: node
    plan: free
    buildCommand: npm_config_prefix=/opt/render/.npm-global npm install -g pnpm && pnpm install --frozen-lockfile && pnpm --filter api exec prisma generate && pnpm --filter api build
    startCommand: node apps/api/dist/src/main.js
    healthCheckPath: /auth/login
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        value: "6379"
      - key: REDIS_TLS
        value: "true"
      - key: REDIS_PASSWORD
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: "1025"
      - key: SMTP_FROM
        sync: false
      - key: VNPAY_TMN_CODE
        value: 6S50MSD6
      - key: VNPAY_HASH_SECRET
        value: HQHOEBWIPCK5O6ABCBAWGU28EDBQSBHS
      - key: VNPAY_URL
        value: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
      - key: VNPAY_RETURN_URL
        value: https://event-ticketing-api-db5k.onrender.com/payments/vnpay-return
      - key: CORS_ORIGIN
        value: https://event-ticketing-hub-eight.vercel.app
      - key: FRONTEND_URL
        value: https://event-ticketing-hub-eight.vercel.app
      - key: BACKEND_URL
        value: https://event-ticketing-api-db5k.onrender.com
      - key: PORT
        value: "3000"
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_ANDROID_CLIENT_ID
        sync: false
